### ISSUE TITLE
Requirements in the README

### ISSUE THREAD

**Issue by maasencioh** [UNArqui17i-B/Delete#2]
I think that instead of having requirements in a .txt files that could be a section on the README

**Comment by NeillGiraldo** [comment]
I can add the requirements to the README,  however I need this file for the dockerfile in line 2 & 3

    ADD requirements.txt /tmp/requirements.txt
    RUN pip install -r /tmp/requirements.txt

or can I do it in a different way?

**Comment by maasencioh** [comment]
oups, you're just right, I don't know any other way
