### ISSUE TITLE
Add at least one test

### ISSUE THREAD

**Issue by maasencioh** [UNArqui17i-B/Delete#8]
Check how complex could be testing in Go

**Comment by NeillGiraldo** [comment]
hahaha this one is in Python, so no problem

**Comment by NeillGiraldo** [comment]
There is no Mock for CouchDB in python, should the tests then run locally?

**Comment by maasencioh** [comment]
You can test REST answers? because you'll always test against localhost

**Comment by NeillGiraldo** [comment]
I usually use flask-testing which allows connection to a real testing-database or mock-database, however, due to the fact that we do not have a deployed testing database yet, I thought, then it has to be with a Mock-database. but ok I will produce the tests for local testing :)

**Comment by NeillGiraldo** [comment]
#10 Pull Request
